# Reference: https://nikitabobko.github.io/AeroSpace/guide

## Various options.

# Start AeroSpace at login.
start-at-login = true

# In the `accordion` layout, pad applications to be visible from underneath
# of each other.
accordion-padding = 20

# Turn off macOS "Hide application" (Cmd-h/Cmd-Alt-h) feature.
# Avoids accidental messing with application windows, which is usually never
# the intentional outcome.
automatically-unhide-macos-hidden-apps = true

# Gaps pixel definitions.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

## Top-level (i.e. accessible all the time) key bindings.
[mode.main.binding]
# Switch to the command mode.
ctrl-a = 'mode command'

# Switch back and forth between the current and the last workspace.
alt-tab = 'workspace-back-and-forth'

## Command mode key bindings.
[mode.command.binding]
# Moving node focus around.
h = ['focus left', 'mode main']
j = ['focus down', 'mode main']
k = ['focus up', 'mode main']
l = ['focus right', 'mode main']

# Moving nodes around.
shift-h = ['move left', 'mode main']
shift-j = ['move down', 'mode main']
shift-k = ['move up', 'mode main']
shift-l = ['move right', 'mode main']

# Send workspaces between monitors.
shift-tab = ['move-workspace-to-monitor --wrap-around next', 'mode main']

# Resize nodes.
# Mnemonic: [M]inus resizing.
m = ['resize smart -50', 'mode main']
# Mnemonic: [P]lus resizing.
p = ['resize smart +50', 'mode main']

# Toggle node layout.
# Mnemonic: [I]ndependent tiles.
i = ['layout tiles vertical horizontal', 'mode main']
# Mnemonic: [O]verlayed tiles.
o = ['layout accordion vertical horizontal', 'mode main']

# Reload configuration.
# Mnemonic: [U]pdate configuration.
u = ['reload-config', 'mode main']

# Switch workspaces.
q = ['workspace q', 'mode main']
w = ['workspace w', 'mode main']
e = ['workspace e', 'mode main']
r = ['workspace r', 'mode main']
t = ['workspace t', 'mode main']
a = ['workspace a', 'mode main']
s = ['workspace s', 'mode main']
d = ['workspace d', 'mode main']
f = ['workspace f', 'mode main']
g = ['workspace g', 'mode main']
z = ['workspace z', 'mode main']
x = ['workspace x', 'mode main']
c = ['workspace c', 'mode main']
v = ['workspace v', 'mode main']
b = ['workspace b', 'mode main']

# Send nodes to specific workspaces.
shift-q = ['move-node-to-workspace q', 'mode main']
shift-w = ['move-node-to-workspace w', 'mode main']
shift-e = ['move-node-to-workspace e', 'mode main']
shift-r = ['move-node-to-workspace r', 'mode main']
shift-t = ['move-node-to-workspace t', 'mode main']
shift-a = ['move-node-to-workspace a', 'mode main']
shift-s = ['move-node-to-workspace s', 'mode main']
shift-d = ['move-node-to-workspace d', 'mode main']
shift-f = ['move-node-to-workspace f', 'mode main']
shift-g = ['move-node-to-workspace g', 'mode main']
shift-z = ['move-node-to-workspace z', 'mode main']
shift-x = ['move-node-to-workspace x', 'mode main']
shift-c = ['move-node-to-workspace c', 'mode main']
shift-v = ['move-node-to-workspace v', 'mode main']
shift-b = ['move-node-to-workspace b', 'mode main']
