# Reference: https://nikitabobko.github.io/AeroSpace/guide

## Various options.

# Start AeroSpace at login.
start-at-login = true

# In the `accordion` layout, pad applications to be visible from underneath
# of each other.
accordion-padding = 20

# Turn off macOS "Hide application" (Cmd-h/Cmd-Alt-h) feature.
# Avoids accidental messing with application windows, which is usually never
# the intentional outcome.
automatically-unhide-macos-hidden-apps = true

# Gaps pixel definitions.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

## Top-level (i.e. accessible all the time) key bindings.
[mode.main.binding]
# Moving node focus around.
ctrl-cmd-h = 'focus left'
ctrl-cmd-j = 'focus down'
ctrl-cmd-k = 'focus up'
ctrl-cmd-l = 'focus right'

# Moving nodes around.
ctrl-alt-h = 'move left'
ctrl-alt-j = 'move down'
ctrl-alt-k = 'move up'
ctrl-alt-l = 'move right'

# Switch back and forth between the current and the last workspace.
ctrl-cmd-tab = 'workspace-back-and-forth'

# Send workspaces between monitors.
ctrl-alt-tab = 'move-workspace-to-monitor --wrap-around next'

# Resize nodes.
# Mnemonic: [M]inus resizing.
ctrl-cmd-m = 'resize smart -50'
# Mnemonic: [P]lus resizing.
ctrl-cmd-p = 'resize smart +50'

# Toggle node layout.
# Mnemonic: [I]ndependent tiles.
ctrl-cmd-i = 'layout tiles vertical horizontal'
# Mnemonic: [O]verlayed tiles.
ctrl-cmd-o = 'layout accordion vertical horizontal'

# Reload configuration.
# Mnemonic: [U]pdate configuration.
ctrl-cmd-u = 'reload-config'

# Switch workspaces.
ctrl-cmd-q = 'workspace q'
ctrl-cmd-w = 'workspace w'
ctrl-cmd-e = 'workspace e'
ctrl-cmd-r = 'workspace r'
ctrl-cmd-t = 'workspace t'
ctrl-cmd-a = 'workspace a'
ctrl-cmd-s = 'workspace s'
ctrl-cmd-d = 'workspace d'
ctrl-cmd-f = 'workspace f'
ctrl-cmd-g = 'workspace g'
ctrl-cmd-z = 'workspace z'
ctrl-cmd-x = 'workspace x'
ctrl-cmd-c = 'workspace c'
ctrl-cmd-v = 'workspace v'
ctrl-cmd-b = 'workspace b'

# Send nodes to specific workspaces.
ctrl-alt-q = 'move-node-to-workspace q'
ctrl-alt-w = 'move-node-to-workspace w'
ctrl-alt-e = 'move-node-to-workspace e'
ctrl-alt-r = 'move-node-to-workspace r'
ctrl-alt-t = 'move-node-to-workspace t'
ctrl-alt-a = 'move-node-to-workspace a'
ctrl-alt-s = 'move-node-to-workspace s'
ctrl-alt-d = 'move-node-to-workspace d'
ctrl-alt-f = 'move-node-to-workspace f'
ctrl-alt-g = 'move-node-to-workspace g'
ctrl-alt-z = 'move-node-to-workspace z'
ctrl-alt-x = 'move-node-to-workspace x'
ctrl-alt-c = 'move-node-to-workspace c'
ctrl-alt-v = 'move-node-to-workspace v'
ctrl-alt-b = 'move-node-to-workspace b'
