# Reference: https://nikitabobko.github.io/AeroSpace/guide

## Various options.

# Start AeroSpace at login.
start-at-login = true

# In the `accordion` layout, pad applications to be visible from underneath
# of each other.
accordion-padding = 20

# Turn off macOS "Hide application" (Cmd-h/Cmd-Alt-h) feature.
# Avoids accidental messing with application windows, which is usually never
# the intentional outcome.
automatically-unhide-macos-hidden-apps = true

# Gaps pixel definitions.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

## Top-level (i.e. accessible all the time) key bindings.
[mode.main.binding]
# Moving node focus around.
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Moving nodes around.
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Switch back and forth between the current and the last workspace.
alt-tab = 'workspace-back-and-forth'

# Send workspaces between monitors.
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Resize nodes.
# Mnemonic: [M]inus resizing.
alt-m = 'resize smart -50'
# Mnemonic: [P]lus resizing.
alt-p = 'resize smart +50'

# Toggle node layout.
# Mnemonic: [I]ndependent tiles.
alt-i = 'layout tiles vertical horizontal'
# Mnemonic: [O]verlayed tiles.
alt-o = 'layout accordion vertical horizontal'

# Reload configuration.
# Mnemonic: [U]pdate configuration.
alt-u = 'reload-config'

# Switch workspaces.
alt-q = 'workspace q'
alt-w = 'workspace w'
alt-e = 'workspace e'
alt-r = 'workspace r'
alt-t = 'workspace t'
alt-a = 'workspace a'
alt-s = 'workspace s'
alt-d = 'workspace d'
alt-f = 'workspace f'
alt-g = 'workspace g'
alt-z = 'workspace z'
alt-x = 'workspace x'
alt-c = 'workspace c'
alt-v = 'workspace v'
alt-b = 'workspace b'

# Send nodes to specific workspaces.
alt-shift-q = 'move-node-to-workspace q'
alt-shift-w = 'move-node-to-workspace w'
alt-shift-e = 'move-node-to-workspace e'
alt-shift-r = 'move-node-to-workspace r'
alt-shift-t = 'move-node-to-workspace t'
alt-shift-a = 'move-node-to-workspace a'
alt-shift-s = 'move-node-to-workspace s'
alt-shift-d = 'move-node-to-workspace d'
alt-shift-f = 'move-node-to-workspace f'
alt-shift-g = 'move-node-to-workspace g'
alt-shift-z = 'move-node-to-workspace z'
alt-shift-x = 'move-node-to-workspace x'
alt-shift-c = 'move-node-to-workspace c'
alt-shift-v = 'move-node-to-workspace v'
alt-shift-b = 'move-node-to-workspace b'
