# Reference: https://nikitabobko.github.io/AeroSpace/guide

## Various options.

# Start AeroSpace at login.
start-at-login = true

# In the `accordion` layout, pad applications to be visible from underneath
# of each other.
accordion-padding = 20

# Turn off macOS "Hide application" (Cmd-h/Cmd-Alt-h) feature.
# Avoids accidental messing with application windows, which is usually never
# the intentional outcome.
automatically-unhide-macos-hidden-apps = true

# Gaps pixel definitions.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

## Top-level (i.e. accessible all the time) key bindings.
[mode.main.binding]
# Moving node focus around.
cmd-ctrl-alt-h = 'focus left'
cmd-ctrl-alt-j = 'focus down'
cmd-ctrl-alt-k = 'focus up'
cmd-ctrl-alt-l = 'focus right'

# Moving nodes around.
cmd-ctrl-alt-comma = 'move left'
cmd-ctrl-alt-period = 'move down'
cmd-ctrl-alt-leftSquareBracket = 'move up'
cmd-ctrl-alt-rightSquareBracket = 'move right'

# Switch back and forth between the current and the last workspace.
cmd-ctrl-alt-tab = 'workspace-back-and-forth'

# Send workspaces between monitors.
cmd-ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Resize nodes.
# Mnemonic: [M]inus resizing.
cmd-ctrl-alt-m = 'resize smart -50'
# Mnemonic: [P]lus resizing.
cmd-ctrl-alt-p = 'resize smart +50'

# Toggle node layout.
# Mnemonic: [I]ndependent tiles.
cmd-ctrl-alt-i = 'layout tiles vertical horizontal'
# Mnemonic: [O]verlayed tiles.
cmd-ctrl-alt-o = 'layout accordion vertical horizontal'

# Reload configuration.
# Mnemonic: [U]pdate configuration.
cmd-ctrl-alt-u = 'reload-config'

# Switch workspaces.
cmd-ctrl-alt-q = 'workspace q'
cmd-ctrl-alt-w = 'workspace w'
cmd-ctrl-alt-e = 'workspace e'
cmd-ctrl-alt-r = 'workspace r'
cmd-ctrl-alt-t = 'workspace t'
cmd-ctrl-alt-a = 'workspace a'
cmd-ctrl-alt-s = 'workspace s'
cmd-ctrl-alt-d = 'workspace d'
cmd-ctrl-alt-f = 'workspace f'
cmd-ctrl-alt-g = 'workspace g'
cmd-ctrl-alt-z = 'workspace z'
cmd-ctrl-alt-x = 'workspace x'
cmd-ctrl-alt-c = 'workspace c'
cmd-ctrl-alt-v = 'workspace v'
cmd-ctrl-alt-b = 'workspace b'

# Send nodes to specific workspaces.
cmd-ctrl-alt-shift-q = 'move-node-to-workspace q'
cmd-ctrl-alt-shift-w = 'move-node-to-workspace w'
cmd-ctrl-alt-shift-e = 'move-node-to-workspace e'
cmd-ctrl-alt-shift-r = 'move-node-to-workspace r'
cmd-ctrl-alt-shift-t = 'move-node-to-workspace t'
cmd-ctrl-alt-shift-a = 'move-node-to-workspace a'
cmd-ctrl-alt-shift-s = 'move-node-to-workspace s'
cmd-ctrl-alt-shift-d = 'move-node-to-workspace d'
cmd-ctrl-alt-shift-f = 'move-node-to-workspace f'
cmd-ctrl-alt-shift-g = 'move-node-to-workspace g'
cmd-ctrl-alt-shift-z = 'move-node-to-workspace z'
cmd-ctrl-alt-shift-x = 'move-node-to-workspace x'
cmd-ctrl-alt-shift-c = 'move-node-to-workspace c'
cmd-ctrl-alt-shift-v = 'move-node-to-workspace v'
cmd-ctrl-alt-shift-b = 'move-node-to-workspace b'
