# Reference: https://nikitabobko.github.io/AeroSpace/guide

# Start AeroSpace at login.
start-at-login = true

# In the `accordion` layout, pad applications to be visible from underneath
# of each other.
accordion-padding = 20

# Turn off macOS "Hide application" (Cmd-h/Cmd-Alt-h) feature.
# Avoids accidental messing with application windows, which is usually never
# the intentional outcome.
automatically-unhide-macos-hidden-apps = true

# Gaps pixel definitions.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# Custom mappings for the main mode.
[mode.main.binding]

# Moving node focus around.
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Moving nodes around.
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize nodes.
alt-leftSquareBracket = 'resize smart -50'
alt-rightSquareBracket = 'resize smart +50'

# Toggle node layout.
alt-shift-leftSquareBracket = 'layout tiles horizontal vertical'
alt-shift-rightSquareBracket = 'layout accordion horizontal vertical'

# Switch workspaces.
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-q = 'workspace q'
alt-w = 'workspace w'
alt-e = 'workspace e'
alt-r = 'workspace r'
alt-t = 'workspace t'
alt-a = 'workspace a'
alt-f = 'workspace f'
alt-g = 'workspace g'

# Send nodes to specific workspaces.
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-q = 'move-node-to-workspace q'
alt-shift-w = 'move-node-to-workspace w'
alt-shift-e = 'move-node-to-workspace e'
alt-shift-r = 'move-node-to-workspace r'
alt-shift-t = 'move-node-to-workspace t'
alt-shift-a = 'move-node-to-workspace a'
alt-shift-f = 'move-node-to-workspace f'
alt-shift-g = 'move-node-to-workspace g'

# Switch back and forth between the current and the last workspace.
alt-tab = 'workspace-back-and-forth'

# Send workspaces between monitors.
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Reload configuration.
alt-shift-semicolon = 'reload-config'

# Switch to application and the workspace it's in quickly.
alt-enter = [
  'exec-and-forget osascript -e "tell application \"Alacritty\"" -e "activate" -e "end tell"',
  'mode main',
]
alt-shift-enter = [
  'exec-and-forget osascript -e "tell application \"Intellij IDEA\"" -e "activate" -e "end tell"',
  'mode main',
]
alt-ctrl-enter = [
  'exec-and-forget osascript -e "tell application \"Chrome\"" -e "activate" -e "end tell"',
  'mode main',
]
